<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <span class="f-left">
		<?php /* @escapeNotVerified */ echo $block->getCopyright() ?>
	</span>
    <span>
        <a href="#">Privacy Policy</a>
    </span>
    <span>
        <a href="#">Terms of Service</a>
    </span>
    <span>
        <a href="#">Sitemap</a>
    </span>
</small>
