<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <span class="f-left" style="margin-right: 24px;color: #ffffff;">
		<?php /* @escapeNotVerified */ echo $block->getCopyright() ?>
	</span>
    <div class="footer-siteinfo">
        <span class="footer-span" style="margin-right: 12px;">
            <a style="color: #ffffff;" href="/privacy-policy">Privacy Policy</a>
        </span>
        <span class="footer-span" style="margin-right: 12px;">
            <a style="color: #ffffff;" href="#">Terms of Service</a>
        </span>
    </div>
</small>
