<?php
/**
 * Magedelight
 * Copyright (C) 2016 Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category Magedelight
 * @package Magedelight_Bundlediscount
 * @copyright Copyright (c) 2016 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

// $block Magedelight\Bundlediscount\Block\Discount
$helper = $this->helper('Magedelight\Bundlediscount\Helper\Data');
$isEnabled = $block->isModuleEnable();
$tags = $block->getTagcategoriesCollection();
$tagUrl = $block->getTagUrl();
$priceHelper = $block->getPriceHelper();
?>
<?php if ($isEnabled): ?>
    <script type="text/javascript">
        var bundles_optionsPrice = [];
    </script>
    <?php
    $bundles = $block->getCollection();
    ?>

<div class="col-main">

    <div class="discount-filter">
        <form action="" method="get">
                <?php
              
                foreach ($tags as $tag):
                    $tagwrappers = $block->getTagwrapperCollection($tag->getEntityId());
                    if ($tagwrappers->count() > 0) {
                        $getTagItems =  $this->getTagItems();
                        $tag_array = explode(',', $getTagItems);
                 
                        ?>
                <div class="tagwrapper-container">
                    <label> <?= /* @noEscape */  $tag->getName();?></label>
                    <div class="tagwrapper-box">
                        <?php
                        foreach ($tagwrappers as $tagwrapper):
                            ?>
                        <div class="tagwrapper-border">
                        <input type="checkbox" onclick="tagwrapper('<?= /* @noEscape */  $tagUrl ?>');" class="tagwrapper" name="tagwrapper[]" value="<?= /* @noEscape */ ($tagwrapper->getId())?>" <?= /* @noEscape */  in_array($tagwrapper->getId(), $tag_array) ? 'checked="checked"' : ''  ?>> <span for=""><?= /* @noEscape */  $tagwrapper->getName()?></span>
                        </div>
                            <?php
                    endforeach;
                        ?>
                        </div>
                        </div>
                        <?php
                    }
                endforeach;
                ?>
        </form>

            <?php
            $getTagItems =  $block->getTagItems();
            $tag_array = explode(',', $getTagItems);
            $serch_content =  $block->getSearchItems();

            if ($serch_content || isset($getTagItems)) {
                $myArray = explode('?', $tagUrl);
                ?>
            <label class="label" for="search" data-role="minisearch-label">
                <a href="<?= /* @noEscape */  $myArray[0];?>"><span>Reset </span></a>
            </label>
            <?php } ?>
            <div class="block block-content discount-filter-box">
               
                    <div class="field search">
                    <?php if (!$serch_content):?>
                        <label class="label" for="search" data-role="minisearch-label">
                            <span>Search </span>
                        </label>
                    <?php else: ?>
                    <label class="label" for="search" data-role="minisearch-label">
                        <span>Search results for: <?= /* @noEscape */  $serch_content; ?> </span>
                    </label>
                    <?php endif;?>  

                        <div class="control">
                            <input id="search_md_tag" type="text" name="qbundle" value="<?= /* @noEscape */  $serch_content; ?>" placeholder="Search Bundle here..." class="input-text" maxlength="128"  >
                            
                          
                            <div  class="actions">
                             <input type="button" onclick="OnSearchSubmit('<?= /* @noEscape */  $tagUrl ?>')" class="action primary"  value="Search">
                            </div>
                        </div>
                    </div>
                
            </div>
    </div> 


    <?php if (!$bundles): ?>
            <p class="note-msg"><?= /* @noEscape */  __('There are no promotions matching the selection.') ?></p>
    <?php else: ?>
        <?= /* @noEscape */  $this->getToolbarHtml(); ?>
        
      
            <div class="products wrapper">
                <div class="page-contents promotions">
                    <div class="prmomtions-contents">
                        <ul>
                            <?php foreach ($bundles as $bundle): ?>
                                <?php

                                $totals = $block->calculateDiscountAmount($bundle);
                                ?>
                                <?php $_selections = $bundle->getSelections(); ?>
                                <?php
                                if (!$_selections) {
                                    continue;
                                }
                                ?>
                                <li class="promotions-lists">
                                    <?php if ($bundle->getName() != ''): ?>
                                        <h3><a href="<?= /* @noEscape */  $bundle->getProductUrl() ?>" title="<?= /* @noEscape */  $bundle->getProductName() ?>"><?= /* @noEscape */  $bundle->getName() ?></a></h3>
                                    <?php endif; ?>
                                    <div class="promotions-discount-container">
                                        <div class="promotions-info">
                                            <?php  if (!$bundle->hasOptions() && !$bundle->hasCustomOptions()): ?>
                                                <p class="price-container">
                                                    
                                                    <span class="old-price bundle_old_price_<?= /* @noEscape */  $bundle->getId() ?>">
                                                        <?= /* @noEscape */  $priceHelper->currency($totals['total_amount'], true, false);

                                                        ?>             
                                                        </span>
                                                       
                                                    <span class="new-price bundle_new_price_<?= /* @noEscape */  $bundle->getId() ?>"><?= /* @noEscape */  $priceHelper->currency($totals['final_amount'], true, false) ?></span>
                                                </p>
                                            <?php  endif; ?>
                                           
                                            <?php if ($bundle->getDiscountType() == '0' || (!$bundle->hasOptions() && !$bundle->hasCustomOptions())): ?>
                                                <p class="discount-info"><?= /* @noEscape */  $totals['discount_label']. ' bundled discount.' ?></p>
                                                <p class="amount-info">
                                                    - <span class="bundle_new_discount_amount_<?= /* @noEscape */  $bundle->getId() ?>">
                                                    <?php  echo $priceHelper->currency($totals['discount_amount'], true, false); ?></span>  bundled discount on buying this offer.
                                                </p>
                                            <?php else: ?>
                                                   <p class="discount-info"><?= /* @noEscape */  $totals['discount_label']. ' discount.' ?></p>

                                            <?php endif; ?>
                                            <?php if ($bundle->canShowAddToCartButton()): ?>
                                                <p class="actions">
                                                    <?php if (!$bundle->hasOptions() && !$bundle->hasCustomOptions()): ?>
                                                        <button class="action primary tocart cart_button_<?= /* @noEscape */  $bundle->getId() ?> " type="button" title="<?= /* @noEscape */  __('Add to Cart') ?>" onclick="addToCart('<?= /* @noEscape */  $block->getBundleAddToCartUrl($bundle->getId()) ?>',<?= /* @noEscape */  $bundle->getId()?>)"><span><span><?= /* @noEscape */  __('Add to Cart') ?></span></span></button>
                                                    <?php else: ?>
                                                        <?php $_configureUrl = $block->getUrl('md_bundlediscount/index/configure', ['bundle_id' => $bundle->getId()]) ?>
                                                        <button class="action primary tocart cart_button_<?= /* @noEscape */  $bundle->getId() ?>" type="button" title="<?= /* @noEscape */  __('Configure') ?>" onclick="configureOptions(<?= /* @noEscape */  $bundle->getId() ?>, '<?= /* @noEscape */  $_configureUrl ?>');"><span><span><?= /* @noEscape */  __('Configure') ?></span></span></button>
                                                    <div id="configure_bundle_<?= /* @noEscape */  $bundle->getId() ?>" class="loading configure_bundle_<?= /* @noEscape */  $bundle->getId() ?>" style="display:none;"></div>
                                                    <?php endif; ?>
                                                </p>
                                            <?php else: ?>
                                                <p class="action availability out-of-stock">
                                                    <span><?= /* @noEscape */  __('Out of stock') ?></span>
                                                </p>
                                            <?php endif; ?>
                                        </div>   
                                         <div class="promotions-selections">
                                            <div class="promotions-selections-img tooltip<?= /* @noEscape */  $bundle->getId() ?>">
                                                <a href="<?= /* @noEscape */  $bundle->getProductUrl() ?>" title="<?= /* @noEscape */  $bundle->getProductName() ?>">
                                                    <img src="<?= /* @noEscape */  $bundle->getImageUrl() ?>" height="90" width="90" /></a>
                                                <div class="promotions-qty">X<?= /* @noEscape */  $bundle->getQty() ?></div>
                                                <div class="tooltip" id="productNameTooltip<?= /* @noEscape */  $bundle->getId() ?>"><?= /* @noEscape */  $bundle->getProductName() ?></div>
                                                <style type="text/css">
                                                    .tooltip<?= /* @noEscape */  $bundle->getId() ?>:hover .tooltip{display:block;position:absolute;top:0;cursor:pointer;}
                                                </style>
                                                <div class="check-configure" style="display: none;">
                                                    <input type="checkbox"  class="custom-check bundle_section_<?= /* @noEscape */  $bundle->getId() ?>" name="flexible_product" value="<?= /* @noEscape */  $bundle->getProductId() ?>" checked=""><label></label></div>
                                              </div>
                                            <div class="promotions-selections-plus">+</div>
                                            <?php $i = 1; ?>
                                            <?php foreach ($_selections as $_selection):
                                                 $configureIds = $helper->loadConfigurableType($_selection->getData('product_id'));
                                                ?>
                                                <div class="promotions-selections-img tooltip<?= /* @noEscape */  $_selection->getId() ?>">

                                                     <?php
                                                        if ($configureIds) {
                                                            $pid = $configureIds[0];
                                                            $purl = $helper->loadMyProductUrl($pid)->getProductUrl()?>
                                                        <a href="<?= /* @noEscape */ $purl ?>" title="<?= /* @noEscape */ $_selection->getProductName() ?>">
                                                            <img src="<?= /* @noEscape */ $_selection->getImageUrl() ?>" height="90" width="90" /></a>
                                                        <?php } else { ?>
                                                            <a href="<?= /* @noEscape */  $_selection->getProductUrl() ?>" title="<?= /* @noEscape */  $_selection->getProductName() ?>">
                                                        <img src="<?= /* @noEscape */  $_selection->getImageUrl() ?>" height="90" width="90" /></a>
                                                    <?php } ?>
                                                    <div class="promotions-qty">X<?= /* @noEscape */  $_selection->getQty() ?></div>
                                                    <div class="tooltip" id="productNameTooltip<?= /* @noEscape */  $_selection->getId() ?>"><?= /* @noEscape */  $_selection->getName() ?></div>
                                                    <style type="text/css">
                                                        .tooltip<?= /* @noEscape */  $_selection->getId() ?>:hover .tooltip{display:block;position:absolute;top:0;;cursor:pointer;}
                                                    </style>
                                                        <?php if ($bundle->getBundleOption() == 'Flexible'): ?>
                                                    <div class="check-configure">
                                                            <?php $_propriceUrl = $block->getUrl('md_bundlediscount/index/custom'); ?>
                                                            <?php if (!$bundle->hasOptions() && !$bundle->hasCustomOptions()): ?>
                                                     <input type="checkbox" onclick="custombundle('<?= /* @noEscape */  $_propriceUrl ?>',<?= /* @noEscape */  $bundle->getId() ?>)" class="custom-check bundle_section_<?= /* @noEscape */  $bundle->getId() ?>" name="flexible_product" value="<?= /* @noEscape */  $_selection->getProductId() ?>" checked="">
                                                        <?php else:?>
                                                    <input type="checkbox" onclick="productcount(<?= /* @noEscape */  $bundle->getId() ?>);" class="custom-check bundle_section_<?= /* @noEscape */  $bundle->getId() ?>" name="flexible_product" value="<?= /* @noEscape */  $_selection->getProductId() ?>" checked="">
                                                        <?php endif; ?>
                                                     <label></label>
                                                 </div>
                                                        <?php else:?>
                                                     <div class="check-configure" style="display: none;">
                                                    <input  type="checkbox" class="custom-check bundle_section_<?= /* @noEscape */  $bundle->getId() ?>" name="flexible_product" value="<?= /* @noEscape */  $_selection->getProductId() ?>" checked="">
                                                    <label></label>
                                                </div>
                                                        <?php endif; ?>
                                                </div>
                                                <?php if ($i < $_selections->count()): ?>
                                                    <div class="promotions-selections-plus">+</div>
                                                    <?php $i++; ?>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        </div>
                                    </div>

                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>

                </div>
            </div>
            <?= /* @noEscape */  $block->getToolbarHtml(); ?>

    <?php endif; ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
require([ 'jquery'], function(){ 
    jQuery(document).ready(function ($) {
        var contents=$('.tagwrapper-container>.tagwrapper-box').hide();
        var titles=$('.tagwrapper-container>label').click(function () {
            titles.not(this).removeClass('active');
            $(this).toggleClass('active');
            contents.not($(this).next()).hide();
            $(this).next().toggle();
            return false;
        });
    });
});
</script>
