<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$imageUrl = $this->helper('Magento\Catalog\Helper\Image')
    ->init($_product, 'product_base_image')
    ->constrainOnly(TRUE)
    ->keepAspectRatio(TRUE)
    ->keepTransparency(TRUE)
    ->keepFrame(FALSE)
    ->resize(800, 800)->getUrl();
$_themeHelper = $this->helper('Codazon\ThemeOptions\Helper\Data');

?>

<!-- <div class="social-addthis" data-media="<?php echo $imageUrl ?>">
      <a href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
	      <span class="icon-facebook fa fa-facebook"></span>
      </a>
      <a href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
	      <span class="icon-twitter fa fa-twitter"></span>
      </a>
	 <a href="https://www.pinterest.com/pin/create/button/?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&media=<?php echo $imageUrl ?>&description=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
	      <span class="icon-pinterest fa fa-pinterest-square"></span>
      </a>
</div>   -->

<div class="custom-payment">
    <picture>
        <source media="(max-width: 428px)" srcset="<?php echo $_themeHelper->getMediaUrl()?>wysiwyg/codazon/fastest_fashion/home/product_payment_mobile.png">
        <img src="<?php echo $_themeHelper->getMediaUrl()?>wysiwyg/codazon/fastest_fashion/home/product_payment.png " alt="">
    </picture>
</div>
<div class="custom-shipping">
    <div class="custom-shipping-infobox">
        <span>Shipping:</span>
        <span>FREE SHIPPING</span>
        <span> on all orders</span>
    </div>
    <a class="custom-style-a" href="/shipping-policy">Learn More</a>
</div>
<div class="custom-proterction">
    <div class="custom-proterction-title">
        <span>Buyer Protection:</span>
        <a class="custom-style-a-mobile" href="#">Learn More</a>
    </div>

    <div class="custom-proterction-contentbox">
        <div class="custom-proterction-contentbox-info1">
            <span>Full refund if you don't receive your order</span>
        </div>
        <div class="custom-proterction-contentbox-info2">
            <span>Full refund if the item is quality defective</span>
            <a class="custom-style-a" href="/return-refund-policy">Learn More</a>
        </div>
    </div>
</div>

<!--<script>-->
<!--    require([ "jquery" ], function($){-->
<!--        $(document).ready(function(){-->
<!--            let mediaTop = $('.product.media').offset().top;-->
<!--            let mediaHeight = $('.product.media').height() - 52;-->
<!--            let mediaBottom = mediaTop + mediaHeight;-->
<!--            $(window).scroll(() => {-->
<!--                var width = $(window).width();-->
<!--                if(width > 1024) {-->
<!--                    if($(window).scrollTop() >= 200){-->
<!--                        let infoBottom = $('.product-info-main').offset().top + $('.product-info-main').height();-->
<!--                        if(mediaBottom <= infoBottom) {-->
<!--                            let scrollTop = $(window).scrollTop();-->
<!--                            let mediaTopAdjust = Math.max((scrollTop - mediaTop), 0);-->
<!--                            let newMediaBottom = mediaTop + mediaTopAdjust + mediaHeight;-->
<!--                            let bottomHeightDiff = infoBottom - mediaBottom;-->
<!--                            if(newMediaBottom <= infoBottom) {-->
<!--                                $('.product.media').css('top','0');-->
<!--                                $('.product.media').css('position', 'fixed');-->
<!--                            } else {-->
<!--                                $('.product.media').css('top', bottomHeightDiff + 'px');-->
<!--                                $('.product.media').css('position', 'relative');-->
<!--                            }-->
<!--                        }-->
<!--                    } else {-->
<!--                        $('.product.media').css('position', 'relative');-->
<!--                        $('.product.media').css('margin-top', "");-->
<!--                    }-->
<!--                }-->
<!--            });-->
<!--        });-->
<!--    });-->
<!--</script>-->
