<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<!-- Event snippet for water-filter.com buy conversion page -->
<!--<script>-->
<!--    gtag('event', 'conversion', {-->
<!--        'send_to': 'AW-746876205/WsFzCMrVtJ8BEK3akeQC',-->
<!--        'transaction_id': ''-->
<!--    });-->
<!--</script>-->

<!-- Event snippet for Order - PC conversion page -->
<!--<script>-->
<!--    newgtag('event', 'conversion', {-->
<!--        'send_to': 'AW-734942208/7VDICNPy06cBEICoud4C',-->
<!--        'transaction_id': ''-->
<!--    });-->
<!--</script>-->

<div class="checkout-success">
	<div class="success-title">
		<p><span class="success-title-icon">icon</span></p>
		<p><span><?php echo __('Thank you!') ?></span></p>
	</div>
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a class="order-id" href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

	<div class="primary">
		<a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
	</div>

</div>

<!-- begin ShareASale.com affiliate tracking -->
<?php
$merchantid = '96131';
$objectManager  =  \Magento\Framework\App\ObjectManager::getInstance();
$orderId        = $block->getOrderId();
$order          = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($orderId);
$subtotal       = $order->getSubtotal();
$discount       = $order->getDiscountAmount();
$affiliateTotal = ($subtotal + $discount);
$ordered_items = $order->getAllVisibleItems();
$skulist = '';
$pricelist = '';
$quantitylist = '';
$last_index = array_search(end($ordered_items), $ordered_items, true);
foreach($ordered_items as $index => $item){
    $delimiter    = $index === $last_index ? '' : ',';
    $skulist      .= $item->getSku() . $delimiter;
    $quantitylist .= ceil($item->getQtyOrdered()) . $delimiter;
    $pricelist    .= ($item->getProduct()->getFinalPrice() - ($item->getDiscountAmount() / $item->getQtyOrdered())) . $delimiter;
}
$couponcodes = $order->getCouponCode();
$newcustomer = '';
$customer = $order->getCustomerId();
if($customer){
    $orderCount =
        $objectManager
            ->create('\Magento\Sales\Model\ResourceModel\Order\CollectionFactory')
            ->create()
            ->addFieldToSelect('*')
            ->addFieldToFilter('customer_id', $customer)
            ->setOrder('created_at','desc')
            ->count();
    $newcustomer = ($orderCount > 1 ? 0 : 1);
}
$currency = $order->getOrderCurrencyCode();
$stateId = trim($order->getShippingAddress()->getData('region_id'));
$region = $objectManager->create('Magento\Directory\Model\Region')->load($stateId);
$regionCode = $region->getCode();

if (array_key_exists("waterdrop_ch", $_COOKIE) && $_COOKIE['waterdrop_ch'] != "ShareASale") {
    $shareasale_channel = true;
} else {
    $shareasale_channel = false;
}
?>

<?php if($shareasale_channel): ?>
    <img id='_SHRSL_img_1' src='https://shareasale.com/sale.cfm?tracking=<?php echo $orderId ?>&amp;amount=<?php echo $affiliateTotal ?>&amp;transtype=sale&amp;merchantID=<?php echo $merchantid ?>&amp;couponcode=<?php echo $couponcodes ?>&amp;skulist=<?php echo $skulist ?>&amp;quantitylist=<?php echo $quantitylist ?>&amp;pricelist=<?php echo $pricelist ?>&amp;newcustomer=<?php echo $newcustomer ?>&amp;currency=<?php echo $currency ?>&amp;v=2.1&amp;autovoid=1' width='1' height='1'>
<?php else: ?>
    <img id='_SHRSL_img_1' src='https://shareasale.com/sale.cfm?tracking=<?php echo $orderId ?>&amp;amount=<?php echo $affiliateTotal ?>&amp;transtype=sale&amp;merchantID=<?php echo $merchantid ?>&amp;couponcode=<?php echo $couponcodes ?>&amp;skulist=<?php echo $skulist ?>&amp;quantitylist=<?php echo $quantitylist ?>&amp;pricelist=<?php echo $pricelist ?>&amp;newcustomer=<?php echo $newcustomer ?>&amp;currency=<?php echo $currency ?>&amp;v=2.1' width='1' height='1'>
<?php endif; ?>

<script src='https://www.dwin1.com/19038.js' type='text/javascript' defer='defer'></script>
<!-- end ShareASale.com affiliate tracking -->

<!-- Event snippet for buy conversion page -->
<script>
    gtag('event', 'conversion', {
        'send_to': 'AW-734942208/TD1KCLb-v-0CEICoud4C',
        'value': <?php echo sprintf("%.2f",$subtotal) ?>,
        'currency': 'USD',
        'transaction_id': '<?php echo $orderId ?>'
    });
    var enhanced_conversion_data = {
        "email": "<?php echo $order->getCustomerEmail() ?>",
        "phone_number": "<?php echo $order->getShippingAddress()->getData('telephone') ?>",
        "first_name": "<?php echo $order->getShippingAddress()->getData('firstname') ?>",
        "last_name": "<?php echo $order->getShippingAddress()->getData('lastname') ?>",
        "home_address": {
            "street": "<?php echo ($order->getShippingAddress()->getStreet()[0] ?? "") ?>",
            "city":"<?php echo $order->getShippingAddress()->getData('city') ?>",
            "region": "<?php echo $regionCode ?>",
            "postal_code": "<?php echo $order->getShippingAddress()->getData('postcode') ?>",
            "country": "<?php echo $order->getShippingAddress()->getData('country_id') ?>"
        }
    }
    gtag('event', 'conversion', {'send_to': 'AW-734942208/TD1KCLb-v-0CEICoud4C'});
</script>

<!-- Bing -->
<script> window.uetq1 = window.uetq1 || []; window.uetq1.push('event', 'purchase', {'revenue_value': '<?php echo sprintf("%.2f",$subtotal); ?>', 'currency': 'USD' }); </script>
<script> window.uetq2 = window.uetq2 || []; window.uetq2.push('event', 'purchase', {'revenue_value': '<?php echo sprintf("%.2f",$subtotal); ?>', 'currency': 'USD' }); </script>
<!-- End Bing -->

<!-- BEGIN GCR Opt-in Module Code -->
<script src="https://apis.google.com/js/platform.js?onload=renderOptIn" async defer></script>
<script>
    window.renderOptIn = function() {
        window.gapi.load('surveyoptin', function() {
            window.gapi.surveyoptin.render(
                {
                    // REQUIRED FIELDS
                    "merchant_id": 135359691,
                    "order_id": "<?php echo $orderId ?>",
                    "email": "<?php echo $order->getCustomerEmail() ?>",
                    "delivery_country": "US",
                    "estimated_delivery_date": "<?php echo date('Y-m-d') ?>",

                    // OPTIONAL FIELDS
                    "products": [
                        <?php foreach($ordered_items as $index => $item): ?>
                            <?php
                                $product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId());
                                $children = $item->getChildrenItems();
                                if ($children) {
                                    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($children[0]->getProductId());
                                }
                            ?>
                            <?php if($product->getData('gtin')): ?>
                            {"gtin":"<?php echo $product->getData('gtin') ?>"},
                            <?php endif; ?>
                        <?php endforeach;?>
                    ]
                });
        });
    }
</script>

<!-- Facebook Purchase track -->
<script>
    require(['jquery'], function ($) {
        $(document).ready(function() {
            setTimeout(function () {
                fbq('track', 'Purchase', {value: <?php echo sprintf("%.2f",$subtotal); ?>, currency: 'USD'});
            }, 5000);
        });
    });
</script>
