<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<style type="text/css">
    .display {
        display: none;
    }
</style>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="wrapper-breadcrums normal">
        <div class="breadcrumbs">
            <ul class="items">
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
                        <?php if ($crumbInfo['link'] && isset($crumbInfo['link'])) : ?>
                            <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
                                <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                            </a>
                        <?php elseif ($crumbInfo['last']) : ?>
                            <strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else: ?>
                            <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="wrapper-breadcrums display">
        <div class="breadcrumbs">
            <ul class="items">
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <?php if ($crumbInfo['link']) : ?>
                        <?php $categoryname = $crumbInfo['title'];?>
                        <?php $categoryurl = $crumbInfo['link'];?>
                    <?php endif;?>
                <?php endforeach; ?>
                <li class="item"><a onclick="Javascript:history(-1);"><&nbsp;&nbsp;&nbsp;</a><a href="<?php echo $categoryurl;?>"><?php echo $categoryname;?></a> </li>
            </ul>
        </div>
    </div>
<?php endif; ?>
