<?php $mediaUrl = $this->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA); ?>
<style>
    .verrified-title {
        background-color: #e8f9ef;
        width: 55%;
        padding: 30px;
        color: #333;
        font-size: 14px;
        line-height: 1.5;
        margin: 0 auto;
        text-align: center;
    }
    .verrified-icon {
        float: left;
        width: 30px;
        height: 30px;
        margin-top: -15px;
    }
    @media (max-width:1300px){
        .parent-div{
            width: 94%;
            margin: 0 auto;
        }
    }
    @media (max-width:1024px) {
        .parent-div {
            width: 90%;
            margin: 0 auto;
        }
    }
    @media (max-width:865px){
        .verrified-title{
            font-size: 12px;
            padding: 25px;
        }
    }
    @media (max-width:767px){
        .verrified-title{
            width: 90%;
        }
    }
    @media (max-width:601px){
        .verrified-title{
            padding: 15px;
        }
    }
    @media (max-width:375px) {
        .verrified-icon {
            margin-top: 0;
            float: none;
        }
    }
</style>
<div class="form-div">
    <!-- VERIFIED -->
    <div class="verrified-title">
        <h3>SUCCEED</h3>
        <span>We have received your gift request. Thanks for choosing Waterdrop!</span>
        <img src="<?php echo $mediaUrl ?>gift/success.png" alt="" class="verrified-icon">
    </div>
</div>