<?php $mediaUrl = $this->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA); ?>
<style>
    .page-header, .page-footer, .cart-footer, .enhanced-privacy-cookie-policy, .wrapper-breadcrums, .block-static-block, .page-title-wrapper {
        display: none !important;
    }
    .page-layout-1column .columns {
        background: transparent;
        box-shadow: none;
        padding: 20px 16px;
    }
    .verrified-title {
        background-color: #e8f9ef;
        width: 100%;
        padding: 30px;
        color: #333;
        font-size: 14px;
        line-height: 1.5;
        margin: 0 auto;
        text-align: center;
    }
    h3 {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-bottom: 12px;
    }
    h3:before {
        font-family: 'icomoon';
        font-size: 32px;
        content: '\e928';
        color: #01B300;
        padding-right: 12px;
    }
</style>
<div class="form-div">
    <!-- VERIFIED -->
    <div class="verrified-title">
        <h3>SUCCEED</h3>
        <div>You have successfully registered your warranty.</div>
        <div>Thanks for choosing our products!</div>
    </div>
</div>
