<style>
    .custom-proterction {
        padding-top: 20px;
    }
    .custom-proterction-contentbox span {
        margin-left: 0;
    }
    .custom-style-a {
        float: right;
        text-decoration: underline;
    }
    .page-title-wrapper {
        display: block !important;
    }
    .page-title-wrapper .page-title {
        margin-top: 24px;
        margin-bottom: 24px;
    }
    @media(max-width: 767px) {
        .custom-proterction {
            padding: 20px 15px 0;
        }
    }
</style>
<div class="custom-proterction">
    <div class="custom-proterction-title">
        <span>Buyer Protection:</span>
        <a class="custom-style-a" href="#">Learn more</a>
    </div>

    <div class="custom-proterction-contentbox">
        <div class="custom-proterction-contentbox-info1">
            <span>Full refund if you don't receive your order</span>
        </div>
        <div class="custom-proterction-contentbox-info2">
            <span>Full refund if the item is not as described</span>
        </div>
    </div>
</div>
