<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/**
 * Brand Slider template
 *
 * @var $block Codazon\Shopbybrandpro\Block\Brand\BrandSlider
 */ ?>
<?php
$orderBy = $block->getConfigValue('codazon_shopbybrand/featured_brands/sort_by');
$sortOrder = $block->getConfigValue('codazon_shopbybrand/featured_brands/sort_order');
$brands = $block->getBrandObject($orderBy, $sortOrder, true);
$count = count($brands);
$i = 0;
$width = $height = 300;
$paddingBottom = 100;
$adapts = array('1900', '1600', '1420', '1280','980','768','480','320','0');
foreach ($adapts as $adapt) {
    $itemPerRow[$adapt] = (float)$this->getData('items_' . $adapt);
}
$widget = ['Codazon_Shopbybrandpro/js/brands' => [
    'codazon.autowidth' => ['itemsPerRow' => $itemPerRow]
]];
?>
<?php if ($count > 0): ?>
<div class="block block-brands">
	<div class="block-title"><strong id="block-brands-heading"><?php echo $block->getConfigValue('codazon_shopbybrand/featured_brands/title') ?></strong></div>
    <div class="block-content">
        <div class="brand-slider-wrapper featured-brands" data-role="slider-wrapper">
            <div class="shop-by-brand-list style-default flex-grid" data-mage-init='<?= json_encode($widget) ?>'>
                <?php foreach ($brands as $brand) : ?>
                    <div class="brand-item" data-role="item">
                        <a class="brand-link abs-img" style="padding-bottom: <?= $paddingBottom ?>%" href="<?= $brand->getUrl() ?>" title="<?= $brand->getBrandLabel(); ?>">
                            <img class="brand-img zoom-eff" alt="<?= strip_tags($brand->getBrandLabel()) ?>" src="<?= $block->getThumbnailImage($brand, ['width' => $width, 'height' => $height]) ?>" />
                        </a>
                    </div>
                    <?php $i++; endforeach ?>
            </div>
        </div>
    </div>
</div>
<?php endif ?>
