<?php
/**
 * Copyright © 2018 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
$helper = $this->helper('Codazon\AjaxLayeredNavPro\Helper\Data');
?>
<?php if ($helper->enableAjaxLayeredNavigation()) : ?>
<?php
$widget = [
    'Codazon_AjaxLayeredNavPro/js/ajaxlayerednavpro' => []
];
$boxMaxHeight = (int)$helper->getConfig('codazon_ajaxlayerednavpro/general/box_max_height');
?>
<div class="product-list-container" id="product-list-container" data-mage-init='<?= json_encode($widget) ?>'>
    <?php echo $this->getChildHtml() ?>
</div>
<?php if ($boxMaxHeight) : ?>
<style type="text/css">
@media(min-width: 768px) {
    .filter-options-content-inner {
        max-height: <?= $boxMaxHeight ?>px;
        overflow-y: auto;
    }
    .filter-options-content-inner::-webkit-scrollbar{
        width: 4px;
        height: 4px;
    }
    .filter-options-content-inner::-webkit-scrollbar-track{
        background: none;
        border-radius: 4px;
    }
    .filter-options-content-inner::-webkit-scrollbar-thumb{
        background: rgba(51, 51, 51, 0.5);
        border-radius: 4px;
    }
    .filter-options-content-inner::-webkit-scrollbar-thumb:hover{
        background: #888;
    }
    .filter-options-content-inner::-webkit-scrollbar-corner{
        background: #179a16;
    }
    .filter-options-content-inner .swatch-attribute-options{margin: 0 0 0 0;}
}
</style>
<?php endif ?>
<?php else : ?>
<?php echo $this->getChildHtml() ?>
<?php endif ?>
<script>
    require(['jquery'],function($){
        $('[data-block="minicart"]').on('contentLoading', function (event) {
            fbq('track', 'AddToCart');
            setTimeout(function() {
                $('html, body').animate({scrollTop:0}, 'slow');
            }, 2000);
        });
    });
</script>
