<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
$_post = $this->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = ($_post->getTitle());
$_postNameStripped = $block->stripTags($_post->getTitle(), null, true);
$width = 840;
$height = 620;
$helper = $this->helper('Magefan\Blog\Helper\Image');
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
        <div class="post-view-title">
            <span><?php echo $_postName; ?></span>
        </div>
        <div class="Subtitle-div">
            <div>
                <div class="post-header detail-post-header">
                    <?php echo $this->getInfoHtml2(); ?>
                </div>
                <div class="blog-date"><?php echo date('F d, Y', strtotime($_post->getData('publish_time'))); ?></span></div>
            </div>
            <div class="addthis_inline_share_toolbox" addthis:url="<?php echo $_postUrl ?>"></div>
        </div>
        <div class="post-image cdz-left">
            <a href="<?php echo $_postUrl ?>">
                <?php
                $featuredImage = $_post->getFeaturedImage();
                $featuredImgAlt = $_postName;?>
                <img class="img-responsive"
                     src="<?= $block->escapeUrl($featuredImage); ?>" alt="<?= $block->escapeUrl($_postName);?>"/>
            </a>
        </div>
        <div class="post-content">
            <div class="post-description">
                <?php echo $block->getContent() ?>
                <div class="clear"></div>
            </div>
        </div>

        <div class="post-bottom">
            <hr class="one-line" align="left"/>
            <div class="addthis_inline_share_toolbox" addthis:url="<?php echo $_postUrl ?>"></div>
        </div>
    </div>
</div>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-61650043458516a6"></script>
