<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php if($block->getProduct()->getCertifiedInfo()): ?>
<style>
    .certified_info {
        font-size: 14px;
        line-height: 16px;
        color: #155DA4;
        margin-bottom: 12px;
    }
</style>
<div class="certified_info">
    <?php /* @escapeNotVerified */ echo $block->getProduct()->getResource()->getAttribute('certified_info')->getFrontend()->getValue($block->getProduct()); ?>
</div>
<?php endif; ?>
<?php if($block->getProduct()->getGtin()): ?>
    <div itemprop="gtin12" style="display: none;"><?php echo $block->getProduct()->getGtin(); ?></div>
<?php endif; ?>
<?php
    $ec_helper = $this->helper('\Ecopure\Catalog\Helper\Data');
    $ec_skus = $ec_helper->getProductSkus($block->getProduct());
?>
<div class="ruk_rating_snippet" data-sku="<?php echo $block->escapeHtml($ec_skus); ?>" style="margin-bottom: 6px;min-height: 0;"></div>
